// Generated by scripts/generate_layered_format.rb. Do not edit.
#ifndef TEBAKO_LAYERED_FORMAT_H
#define TEBAKO_LAYERED_FORMAT_H

#include <cstddef>
#include <cstdint>

namespace tebako::layered_format {
inline constexpr std::uint16_t major_version = 1;
inline constexpr std::uint16_t minor_version = 0;
inline constexpr char magic[] = "TEBAKOL1";
inline constexpr std::size_t magic_size = sizeof(magic) - 1;
inline constexpr std::size_t footer_size = sizeof(std::uint64_t) + magic_size;
}  // namespace tebako::layered_format

#endif
