// Generated by scripts/generate_layered_format.rb. Do not edit.
#ifndef TEBAKO_SINGLE_FILE_BUNDLE_FORMAT_H
#define TEBAKO_SINGLE_FILE_BUNDLE_FORMAT_H

#include <cstddef>
#include <cstdint>

namespace tebako::single_file_bundle_format {
inline constexpr std::uint16_t major_version = 1;
inline constexpr std::uint16_t minor_version = 0;
inline constexpr char magic[] = "TEBAKOB1";
inline constexpr std::size_t magic_size = sizeof(magic) - 1;
inline constexpr std::size_t digest_size = 32;
inline constexpr std::size_t footer_size = sizeof(std::uint64_t) + digest_size + magic_size;
}  // namespace tebako::single_file_bundle_format

#endif
