#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates the Ruby and C++ constants shared by the layered package codec.

require "json"

root = File.expand_path("..", __dir__)
schema = JSON.parse(File.binread(File.join(root, "format", "layered_package.json")))
bundle_schema = JSON.parse(File.binread(File.join(root, "format", "single_file_bundle.json")))
magic = schema.fetch("magic")
major = schema.fetch("major_version")
minor = schema.fetch("minor_version")
bundle_magic = bundle_schema.fetch("magic")
bundle_major = bundle_schema.fetch("major_version")
bundle_minor = bundle_schema.fetch("minor_version")

ruby = <<~RUBY
  # frozen_string_literal: true

  # Generated by scripts/generate_layered_format.rb. Do not edit.
  module Tebako
    module Generated
      module LayeredFormat
        MAJOR_VERSION = #{major}
        MINOR_VERSION = #{minor}
        MAGIC = #{magic.inspect}
        MAGIC_SIZE = #{magic.bytesize}
        FOOTER_SIZE = #{magic.bytesize + 8}
      end
    end
  end
RUBY

cpp = <<~CPP
  // Generated by scripts/generate_layered_format.rb. Do not edit.
  #ifndef TEBAKO_LAYERED_FORMAT_H
  #define TEBAKO_LAYERED_FORMAT_H

  #include <cstddef>
  #include <cstdint>

  namespace tebako::layered_format {
  inline constexpr std::uint16_t major_version = #{major};
  inline constexpr std::uint16_t minor_version = #{minor};
  inline constexpr char magic[] = "#{magic}";
  inline constexpr std::size_t magic_size = sizeof(magic) - 1;
  inline constexpr std::size_t footer_size = sizeof(std::uint64_t) + magic_size;
  }  // namespace tebako::layered_format

  #endif
CPP

bundle_ruby = <<~RUBY
  # frozen_string_literal: true

  # Generated by scripts/generate_layered_format.rb. Do not edit.
  module Tebako
    module Generated
      module SingleFileBundleFormat
        MAJOR_VERSION = #{bundle_major}
        MINOR_VERSION = #{bundle_minor}
        MAGIC = #{bundle_magic.inspect}
        MAGIC_SIZE = #{bundle_magic.bytesize}
        DIGEST_SIZE = 32
        FOOTER_SIZE = #{bundle_magic.bytesize + 8 + 32}
      end
    end
  end
RUBY

bundle_cpp = <<~CPP
  // Generated by scripts/generate_layered_format.rb. Do not edit.
  #ifndef TEBAKO_SINGLE_FILE_BUNDLE_FORMAT_H
  #define TEBAKO_SINGLE_FILE_BUNDLE_FORMAT_H

  #include <cstddef>
  #include <cstdint>

  namespace tebako::single_file_bundle_format {
  inline constexpr std::uint16_t major_version = #{bundle_major};
  inline constexpr std::uint16_t minor_version = #{bundle_minor};
  inline constexpr char magic[] = "#{bundle_magic}";
  inline constexpr std::size_t magic_size = sizeof(magic) - 1;
  inline constexpr std::size_t digest_size = 32;
  inline constexpr std::size_t footer_size = sizeof(std::uint64_t) + digest_size + magic_size;
  }  // namespace tebako::single_file_bundle_format

  #endif
CPP

File.write(File.join(root, "lib", "tebako", "generated", "layered_format.rb"), ruby)
File.write(File.join(root, "include", "tebako", "layered-format.h"), cpp)
File.write(File.join(root, "lib", "tebako", "generated", "single_file_bundle_format.rb"), bundle_ruby)
File.write(File.join(root, "include", "tebako", "single-file-bundle-format.h"), bundle_cpp)
